### ISSUE TITLE
OpenVPN not found: /usr/sbin/openvpn

### ISSUE THREAD

**Issue by xinthose** [TinCanTech/easy-tls#106]
I am following the [Easy-RSA v3 OpenVPN Howto](https://community.openvpn.net/openvpn/wiki/EasyRSA3-OpenVPN-Howto?) and I am on this step: `./easytls build-tls-auth`, but I get this error: `OpenVPN not found: /usr/sbin/openvpn`, so I run `which openvpn` after installing it and it shows me this: `/usr/local/sbin/openvpn`, so I run the build command like this: `./easytls build-tls-auth --openvpn="/usr/local/sbin/openvpn"` and I get the same error.  I tried without quotation marks too: `./easytls build-tls-auth --openvpn=/usr/local/sbin/openvpn`.  What am I doing wrong?

**Comment by TinCanTech** [comment]
Hi, as with EasyRSA, the --option should be written before the copmmand option:

`./easytls --openvpn=/usr/local/sbin/openvpn build-tls-auth`

**Comment by xinthose** [comment]
Oh, I see.  That worked.  Thank you!

**Comment by TinCanTech** [comment]
I think the script should **not** set:
`set_var EASYTLS_OPENVPN		"/usr/sbin/openvpn"`

This was set this way during development because I used `git/master/openvpn` for TLS-Crypt-V2 keys because the release version OpenVPN 2.4.x did not support those keys.

Now that OpenVPN 2.5 is released this variable ought to be set like so:
`set_var EASYTLS_OPENVPN		"openvpn"`

@xinthose Thanks for using Easy-TLS and thanks for bringing my attention to this.

**Comment by xinthose** [comment]
@TinCanTech that sounds better to me; I installed openvpn from source, so the command is in `/usr/local/sbin/openvpn`, not `/usr/sbin/openvpn`.  The current version on Ubuntu 20.04 LTS is 2.4.7 and not 2.5.0 which has the `tls-crypt-v2` parameter.

**Comment by TinCanTech** [comment]
All feedback welcome

**Comment by TinCanTech** [comment]
The "Fix" was not a real fix. This needs further work.

**Comment by TinCanTech** [comment]
@xinthose how does it look to you ?

**Comment by xinthose** [comment]
@TinCanTech I am not sure.  Does `verify_openvpn` find the path to the openvpn executable in Linux?  You can find that with `which openvpn`.  That command gives `/user/local/sbin/openvpn` for me even if I have installed the lower version with `apt install openvpn`.  Then you can use that path with the `--version` option to find the version being used by the user.

**Comment by TinCanTech** [comment]
Of course, `which` is the proper way but `which.exe` for Windows is not worth the effort.

EasyRSA3 detects `openssl` the same way as Easy-TLS does here for `openvpn`.

The problem which https://github.com/TinCanTech/easy-tls/commit/f57b3cc591e85e48fcca4adb42687295834d656d addressed is:
Using `[ -f openvpn ]` fails because it does not search PATH but sub-shelling out to run whatever `openvpn` is installed does work.  And also works on Windows.

**Comment by xinthose** [comment]
OK.  LGTM.

**Comment by TinCanTech** [comment]
Thank you.
